brightness: 16
contrast: 0
curve: Polynomial
exposure: 50
fformat: png
gamma: 100
hue: 0
levelrange_high:
- 255
- 255
- 255
- 255
levelrange_low:
- 0
- 0
- 0
- 0
linear: 0
saturation: 96
sharpening: 500
temp: 6503
tint: 1000
wbgain:
- 0
- 0
- 0
