auto_expo: 0
brightness: 64
contrast: 10
curve: Polynomial
exposure: 120
fformat: tif
gamma: 100
hue: -2
levelrange_high:
- 255
- 255
- 255
- 255
levelrange_low:
- 0
- 0
- 0
- 0
linear: 0
saturation: 126
sharpening: 500
temp: 11616
tint: 925
wbgain:
- 0
- 0
- 0
