auto_expo: 0
brightness: 60
contrast: 15
curve: Polynomial
exposure: 120
fformat: tif
gamma: 100
hue: -7
levelrange_high:
- 255
- 255
- 255
- 255
levelrange_low:
- 0
- 0
- 0
- 0
linear: 0
saturation: 42
sharpening: 500
temp: 11616
tint: 925
wbgain:
- 0
- 0
- 0
