brightness: 16
contrast: 0
curve: 1
exposure: 50
gamma: 100
hue: 0
levelrange_high:
- 255
- 255
- 255
- 255
levelrange_low:
- 0
- 0
- 0
- 0
linear: 0
saturation: 128
sharpening: 500
temp: 6503
tint: 1000
wbgain:
- 0
- 0
- 0
